
service: sequelize-crud-demo-apis

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  iamRoleStatements: [
  {
    "Effect": "Allow",
    "Action": [
        "lambda:InvokeFunction"
    ],
    "Resource": "*"
  },
  {
    "Effect": "Allow",
    "Action": [
        "dynamodb:*"
    ],
    "Resource": "*"
  },
  {
    "Effect": "Allow",
    "Action": [
        "s3:*"
    ],
    "Resource": "*"
  }
]

plugins:
  - serverless-offline



functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
